version: '2'
services:

  moodle_db:
    image: wodby/mariadb:10.1-2.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: moodle_db
      PMA_USER: root
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8002:8025"

  moodle:
    image: 'pauloamgomes/moodle-php:7.0'
    # image: 'pauloamgomes/moodle-php:5.6'
    # Moodle version (e.g. 3.1.4, 3.2.1, 3.2.2, 3.2.3, 3.3.0)
    environment:
      MOODLE_VERSION: "3.3.0"
      MOODLE_HOSTNAME: "localhost"
      MOODLE_DB_NAME: "moodle"
      MOODLE_DB_USER: "root"
      MOODLE_DB_PASS: "root"
      MOODLE_DB_HOST: moodle_db
      MOODLE_USER: "admin"
      MOODLE_PASS: "admin123"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - moodle-sync:/var/www/moodle:nocopy
    depends_on:
      - moodle_db

volumes:
  moodle-sync:
    external: true
